config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :movies

    validates  :name,  presence: true ,  length: {minimum:3}
    validates :age,  presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :client

  validates  :name,  presence: true ,  length: {minimum:3}

  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  include Pagy::Backend
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  before_action :set_movie

  # GET /clients or /clients.json
  def index
    @pagy, @clients = pagy(Client.all)
    # @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Cliente creado correctamente." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Cliente actualizado correctamente." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy!

    respond_to do |format|
      format.html { redirect_to clients_path, status: :see_other, notice: "Cliente ha sido eliminado" }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    def set_movie
      @movies = Movie.all 
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :set_clients

  # GET /movies or /movies.json
  def index
    # @movies = Movie.all
    @pagy, @movies = pagy(Movie.all)
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
    # @clientss = clients.all.pluck :name, :id
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy!

    respond_to do |format|
      format.html { redirect_to movies_path, status: :see_other, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def set_clients
      @clients = Client.all 
      # @clients = Client.find(params[:clients_id])
    end
    

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :client_id)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/clients_helper.rb
module ClientsHelper

end

app/helpers/movies_helper.rb
module MoviesHelper


end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <%# <p>
    <strong>Name:</strong>
    <%= client.name %>
  <%# </p> %>
<%# 
  <p> %>
    <%# <strong>Age:</strong> %>
    <%# <%= client.age %>
  <%# </p> %>


<%# ------------------------------------ %>
    <tr >
          <td class = "text-danger"><%= client.id %></td>
          <td class = "text-danger"><%= client.name  %></td>
          <td class = "text-danger"><%= client.age %></td>
        

          <td><%= link_to client, class: 'btn' do  %>
              <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-eye-check" width="20" 
                  height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="#00abfb" fill="none" 
                  stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <circle cx="12" cy="12" r="2" />
                  <path d="M12 19c-4 0 -7.333 -2.333 -10-7c2.667 -4.667 6 -7
                10 -7s7.333 2.333 10 7c-.42 .736 -.858 1.414 -1.311 2.033" />
                  <path d="M15 19l2 2l4 -4" />
              </svg>
            <% end %>
          </td>
          <td><%= link_to edit_client_path(client), class: 'btn' do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit" width="20" 
                height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffec00" fill="none" 
                stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M9 7h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2-2v-3" />
                <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0-3 -3l-8.5 8.5v3" />
                <line x1="16" y1="5" x2="19" y2="8" />
              </svg>
            <% end %>
          </td>
      </tr>


</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

        <div class= "row  justify-content-evenly ">
            <%# <div class="card col-12 col-sm-5 col-md-3 col-lg-3  "  %>
          <div class="card col-12 col-sm-8 col-md-6  "  
                style="border:2px solid Tomato; background-color:rgb(208, 211, 212);">
              <div class="card-body ">
                    <h5 class="card-title"> clientes <%= @client.id %> </h5>
                    <div>
                          <div>
                            <%= form.label :name, style: "display: block" %>
                            <%= form.text_field :name %>
                          </div>
                          <div>
                            <%= form.label :age, style: "display: block" %>
                            <%= form.text_field :age %>
                          </div>
                  <div class = "d-flex justify-content-end mt-3 gap-3"> 
                    <%= form.submit class: "btn btn-success px-5 py-3  fw-lith " %>
                    <%= link_to "volver cliente", clients_path, class: "btn btn-info  px-5 py-2  fw-lith " %>
                <div>
            <div>
          <div>
        </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<% content_for :title, "Editing client" %>

<h2 class="contanier text-white text-center "> Editar Cliente </h2>

<%= render "form", client: @client %>

<br>

<div>
  <%#= link_to "Show this client", @client %> 
  <%#= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Clientes" %>

<h2 class="contanier text-white text-center "> **  Clientes ** </h2>


<div class = "container d-flex justify-content-end mt-3 gap-3"> 
    <%== pagy_bootstrap_nav(@pagy) %>
    <%= link_to "Crear Cliente", new_client_path, class: "btn btn-success px-4 py-3  "%>
</div>

<div id="clients ">
    <div class="container">
        <table class="table table-striped">
          <thead>
            <tr style="background-color:DodgerBlue;" class = "text-center text-tomato">
              <th scope="col ">id</th>
              <th scope="col">Name</th>
              <th scope="col">Age</th>
              <th scope="col" colspan="2"></th>
            </tr>
          </thead>

          <tbody  class = "text-center ">
             <% @clients.each do |client| %>
                <div class = "text-danger">
                      <%= render client, class: " text-danger" %>
                  </div>  
                  <div class = "text-warning">
                    <th scope="col " class = "text-warning">Pelicula Arrendada</th>
                      <td class = "text-white"> <%= client.movies.last.name    %>
                  </div> 
                <%end%>
          </tbody>

        </table>
    </div>
</div>
<div class = "container d-flex justify-content-end mt-3 gap-3 "> 
 <%== pagy_bootstrap_nav(@pagy) %>
    <%= link_to "Crear Cliente", new_client_path, class: "btn btn-success px-4 py-3 " %>
</div>

app/views/clients/new.html.erb
<% content_for :title, "Nuevo cliente" %>

<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>

</div>

app/views/clients/show.html.erb
<%# <p style="color: green"><%= notice %>
<%# </p>  %>

<%#= render @client %>

<div>
      <h2 class="contanier text-white text-center "> Ver Cliente</h2>

      <p style="color: red" class=" col text-center"><%= notice %></p>

      <div id="clients"  class = "container mt-3  mb-5  text-primary ">
          <div class= "row  justify-content-evenly ">
                <%# <div class="card col-12 col-sm-5 col-md-3 col-lg-3  "  %>
                <div class="card col-12 col-sm-10 col-md-7 col-lg-7 "  
                    style="border:2px solid Tomato; background-color:rgb(208, 211, 212);">
                  <%# <img src="..." class="card-img-top" alt="..."> %>
                  <div class="card-body text-center">
                    <h5 class="card-title">Cliente Id ==>  <%= @client.id %> </h5>
                        
                        <%# <p> ID    :  <%= @client.id %> </p>
                        <p> Cliente     :  <%= @client.name%> </p>
                        <p> Edad     :  <%= @client.age%> </p>
                    
                  <div class= "container  d-flex justify-content-between  gap-3 align-items-center">
                      <%= link_to "Editar Cliente", edit_client_path(@client), class: "btn btn-success"%> 
                      <%= link_to "Retornar Cliente", clients_path, class: "btn btn-info"%> 
                      <%= button_to "Eliminar Cliente", @client, method: :delete, class: "btn btn-danger" %>


                       <%= link_to "Ir a pelicula ", movies_path, class: "btn btn-secondary " %>
                  </div>
      <div>



  <%#= link_to "Edit this client", edit_client_path(@client) %> 
  <%#= link_to "Back to clients", clients_path %>

  <%#= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blockbuster" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
     <script src="https://kit.fontawesome.com/e8f733cf95.js" crossorigin="anonymous"></script>

  </head>

  <body class="contanier text-white">
    <h1 class="contanier text-info text-center "> Blockbuster </h1>
     <div  class=" ">

          <%= yield %>

    </div>

    

             <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" 
         integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
         
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" 
          integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div id="movies"  class = "container mt-3  mb-5  text-primary ">
      <div class= "row  justify-content-evenly ">
            <div class="card col-12 col-sm-8 col-md-6  "  
                style="border:2px solid Tomato; background-color:rgb(208, 211, 212);">
              <div class="card-body ">

                <div>
                  <%= form.label :Pëlicula, style: "display: block" %>
                  <%= form.text_field :name %>
                </div>

                <div>
                    <%= form.label :Cliente, style: "display: block" %>
                    <%= form.collection_select :client_id, @clients, :id, :name, { prompt: "Selecciona un Cliente" }  %>
                </div>

                <div class = "d-flex justify-content-end mt-3 gap-3"> 
                    <%= link_to "Retonar Pelicula", movies_path, class: "btn btn-info  px-3 py-2  fw-lith "  %>
                    <%= form.submit class: "btn btn-success px-2 py-2 fw-lith " %>
                </div>
              </div>
        
            </div>  
      </div>
    </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>"  class = "text-white">
 
<%# ------------------------------------ %>
    <tr >
          <td class = "text-danger"><%= movie.id %></td>
          <td class = "text-danger"><%= movie.name %></td>
          <td class = "text-danger"><%= movie.client_id %></td>
          <td class = "text-danger"><%= movie.client.name%>  </td> 

          <td><%= link_to movie, class: 'btn' do  %>
              <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-eye-check" width="20" 
                  height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="#00abfb" fill="none" 
                  stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <circle cx="12" cy="12" r="2" />
                  <path d="M12 19c-4 0 -7.333 -2.333 -10-7c2.667 -4.667 6 -7
                10 -7s7.333 2.333 10 7c-.42 .736 -.858 1.414 -1.311 2.033" />
                  <path d="M15 19l2 2l4 -4" />
              </svg>
            <% end %>
          </td>
          <td><%= link_to edit_movie_path(movie), class: 'btn' do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit" width="20" 
                height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffec00" fill="none" 
                stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M9 7h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2-2v-3" />
                <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0-3 -3l-8.5 8.5v3" />
                <line x1="16" y1="5" x2="19" y2="8" />
              </svg>
            <% end %>
          </td>
      </tr>


</div>

app/views/movies/edit.html.erb
<% content_for :title, "Editing movie" %>

<h2 class="contanier text-white text-center "> Editar Pelicula</h2>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> 
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Movies" %>

<h2 class="contanier text-white text-center ">**  Peliculas  **</h2>


<div class = "container col d-flex justify-content-end mt-3 mb-3 gap-3 "> 
        <%== pagy_bootstrap_nav(@pagy) %>

    <%= link_to "Volver a cliente", clients_path, class: "btn btn-info    px-3 py-2 fw-lith   "%>
    <%= link_to "Nueva Pelicula", new_movie_path, class: "btn btn-success px-3 py-2  fw-lith "%>
</div>


 <div id="movies">
    <div class="container text-white">
        <table class="table table-striped text-white">
          <thead>
            <tr style="background-color:DodgerBlue;" class = "text-center text-white">
              <th scope="col ">id</th>
              <th scope="col">Name</th>
              <th scope="col">Cliente ID</th>
              <th scope="col">Nombre Cliente</th>
              <th scope="col" colspan="2"></th>
            </tr>
          </thead>
          <tbody  class = "text-center text-red">
             <% @movies.each do |movie| %>
                <%= render movie %>

             <%end%>
          </tbody>
        </table>
      </div>
</div>

<div class = "container d-flex justify-content-end mt-3 gap-3 my-5"> 
   <div class = " d-flex justify-content-between "  >
        <%# <%== pagy_bootstrap_nav(@pagy) %>
        <%== pagy_bootstrap_nav(@pagy)%>

    </div>
    <%= link_to "Volver a cliente", clients_path, class: "btn btn-info    px-3 py-2  fw-lith "%>
    <%= link_to "Nueva Pelicula", new_movie_path, class: "btn btn-success px-3 py-2  fw-lith "%>

</div>

app/views/movies/new.html.erb
<% content_for :title, "New movie" %>

<h2 class="contanier text-white text-center "> Nueva Pelicula</h2>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<%# <%= render @movie %>
<h2 class="contanier text-white text-center "> Ver Pelicula</h2>

<p style="color: red" class=" col text-center"><%= notice %></p>

<div id="movies"  class = "container mt-3  mb-5  text-primary ">
    <div class= "row  justify-content-evenly ">
          <%# <div class="card col-12 col-sm-5 col-md-3 col-lg-3  "  %>
          <div class="card col-12 col-sm-10 col-md-7 col-lg-7 "  
              style="border:2px solid Tomato; background-color:rgb(208, 211, 212);">
            <%# <img src="..." class="card-img-top" alt="..."> %>
            <div class="card-body text-center">
              <h5 class="card-title">Pelicula Id ==>  <%= @movie.id %> </h5>
                  
                   <p> Pelicula    :  <%= @movie.name %> </p>
                   <p> Cliente     :  <%= @movie.client.name%> </p>
               
            <div class= "container  container d-flex justify-content-between  align-items-center">
                <%= link_to "Editar Pelicula", edit_movie_path(@movie), class: "btn btn-success"%> 
                <%= link_to "Retornar pelicula", movies_path, class: "btn btn-info"%> 
                <%= button_to "Eliminar Pelicula", @movie, method: :delete, class: "btn btn-danger" %>
            </div>
<div>

</div>